### ISSUE TITLE
yarn add canaskit-oc does not work. (not registered)

### ISSUE THREAD

**Issue by softmarshmallow** [udevbe/canvaskit-oc#3]
yarn add canaskit-oc

 yarn add canaskit-oc

yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/canaskit-oc: Not found".

**Comment by Zubnix** [comment]
yarn add can**v**askit-oc
:wink:

**Comment by Zubnix** [comment]
readme fixed & updated
